# Generated by Django 6.0.5 on 2026-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='jira_issue_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workitem',
            name='jira_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='jira_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workitem',
            name='jira_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workitem',
            name='jira_url',
            field=models.URLField(blank=True),
        ),
    ]
