# Generated by Django 6.0.5 on 2026-05-20 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workitem_jira_issue_type_workitem_jira_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='feature_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workitem',
            name='feature_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workitem',
            name='feature_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='WorkItemMonthlyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('budget_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_values', to='core.workitem')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('work_item', 'month')},
            },
        ),
    ]
