# Generated by Django 6.0.5 on 2026-05-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workitem_feature_key_workitem_feature_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='charge_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
