# Generated by Django 6.0.5 on 2026-05-28 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workitem_charge_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyETC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('etc_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_etcs', to='core.workitem')),
            ],
            options={
                'unique_together': {('work_item', 'month')},
            },
        ),
    ]
