# Generated by Django 6.0.5 on 2026-06-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_monthlyetcchange_delete_budgetchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyetcchange',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
