# Generated by Django 6.0.5 on 2026-06-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_monthlyetcchange_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='baseline_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
