# Generated by Django 6.0.5 on 2026-06-04 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workitem_baseline_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='core.workitem')),
            ],
        ),
    ]
